In [2]:
from xgboost import XGBClassifier

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv('diabetes.csv')

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [7]:
y=df.Outcome
x=df.drop('Outcome',axis=1)

In [9]:
model=XGBClassifier()

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [27]:
model.fit(xtrain,ytrain,eval_metric='logloss')

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [28]:
ypred=model.predict(xtest)

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [30]:
confusion_matrix(ytest,ypred)

array([[71, 17],
       [24, 42]], dtype=int64)

In [31]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.75      0.81      0.78        88
           1       0.71      0.64      0.67        66

    accuracy                           0.73       154
   macro avg       0.73      0.72      0.72       154
weighted avg       0.73      0.73      0.73       154



In [32]:
accuracy_score(ytest,ypred)

0.7337662337662337

In [33]:
df=sns.load_dataset('iris')

In [34]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le=LabelEncoder().fit_transform(df.species)

In [38]:
df.species = le

In [39]:
x=df.drop('species',axis=1)
y=df.species

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [45]:
model.fit(xtrain.values,ytrain.values)

[22:23:41] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Shahdab\anaconda3\envs\tf\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [47]:
ypred=model.predict(xtest.values)
ypred

array([1, 1, 0, 2, 1, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 1,
       1, 2, 2, 0, 1, 0, 1, 2])

In [48]:
accuracy_score(ypred,ytest)

0.9666666666666667

In [50]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.89      1.00      0.94         8
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [51]:
confusion_matrix(ytest,ypred)

array([[11,  0,  0],
       [ 0,  8,  0],
       [ 0,  1, 10]], dtype=int64)